print('    xxxxxxxxx')
print(' xxxxxxxxxxxxxxx')
print('xxxxxxxxxxxxxxxxx')
print('xxxxxxxxxxxxxxxxx')
print('xxxxxxxxxxxxxxxxx')
print(' xxxxxxxxxxxxxxx ')
print('  xxxxxxxxxxxxx  ')
print('   xxxxxxxxxxx   ')
print('    xxxxxxxxx    ')
print('       xxx       ')
print('       xxx       ')
print('       xxx       ')
print('       xxxx      ')
print(' xxxxxxxxxxxxxxx ')
print('  xxxxxxxxxxxxx  ')
print('   xxxxxxxxxxx   ')
      
